services:
  postgres:
    container_name: db_sth_co
    build:
      context: ./sth-docker/database
    image: sth/postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-sth}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_DB: "${POSTGRES_DB:-sth_mainnet}"
      POSTGRES_VERSION: "${POSTGRES_VERSION:-18}"
    # ✅ Use new mount path for PostgreSQL 18+
    volumes:
      - ./pgdata:/var/lib/postgresql
    networks:
      appnet:
        ipv4_address: 10.10.10.11
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sth} -d ${POSTGRES_DB:-sth_mainnet}"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Let the default entrypoint handle DB init scripts inside /docker-entrypoint-initdb.d
    command: ["postgres"]

volumes:
  pgdata:

networks:
  appnet:
    external: true