services:
  postgres:
    container_name: db_sth_co
    build:
      context: ./sth-docker/database
      dockerfile: ./Dockerfile.offline
    image: sth/postgres:18
    restart: "no"
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-sth}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_DB: "${POSTGRES_DB:-sth_mainnet}"
      POSTGRES_VERSION: "${POSTGRES_VERSION:-18}"
    networks:
      appnet:
        ipv4_address: 10.10.10.11
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sth} -d ${POSTGRES_DB:-sth_mainnet}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["postgres"]

networks:
  appnet:
    external: true